### ISSUE TITLE
Pool address error

### ISSUE THREAD

**Issue by filipporomani** [superpythonguy/hydrocoin#1]
The script doesn't connect to the server! It seems to be a wrong ip. I suggest you to use cloudflare tunnels/ngrok.io

**Comment by superpythonguy** [comment]
oh right now i am developing the server so expect some downtime

**Comment by superpythonguy** [comment]
sorry about this

**Comment by filipporomani** [comment]
ok! is there a discord server for this?

**Comment by superpythonguy** [comment]
yes at https://discord.gg/ytPgbVjZSs
